ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH  = /usr/bin
TARGET  = sample
BOARD   = uno
#MCU     = atmega328p
#F_CPU   = 16000000
ARDUINO_PORT    = /dev/ttyACM0
AVRDUDE_CONF = $(ARDUINO_DIR)/hardware/tools/avrdude.conf
AVRDUDE_ARD_PROGRAMMER = arduino
include ../Arduino.mk
